package Admin;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Ventana de la ficha de un coche
 */
public class CarWindow extends javax.swing.JFrame {

    /**
     * Coche del que tiene información esta ventana
     */
    private final CarModel car;
    
    /**
     * Creates new form Descripcion
     * @param car Coche a mostrar en el formulario
     */
    public CarWindow(CarModel car) {
        initComponents();
        this.car = car;
        campoNombre.setText(car.getName());
        campoAsientos.setText(""+car.getNumberSeats());
        campoCategoria.setText(car.getCategory());
        campoCombustible.setText(car.getFuelType());
        campoConsumo.setText(""+car.getConsumption());
        campoPotencia.setText(""+car.getPower());
        campoPrecio.setText(""+car.getCost());
        campoPuertas.setText(""+car.getNumberDoors());
        
        destacado.setSelected(car.getFeatured());
        //falta ponerle un boolean si esta destacado o no
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Combustible = new javax.swing.JLabel();
        Potencia = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Consumo = new javax.swing.JLabel();
        Puertas = new javax.swing.JLabel();
        Asientos = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoCombustible = new javax.swing.JTextField();
        campoPotencia = new javax.swing.JTextField();
        campoCategoria = new javax.swing.JTextField();
        campoConsumo = new javax.swing.JTextField();
        campoPuertas = new javax.swing.JTextField();
        campoAsientos = new javax.swing.JTextField();
        campoPrecio = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Contacto = new javax.swing.JLabel();
        cmpApellidosContacto = new javax.swing.JTextField();
        cmpNombreContacto = new javax.swing.JTextField();
        NombreContacto = new javax.swing.JLabel();
        ApellidosContacto = new javax.swing.JLabel();
        MailContacto = new javax.swing.JLabel();
        cmpMailContacto = new javax.swing.JTextField();
        CiudadContacto = new javax.swing.JLabel();
        cmpCiudadContacto = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        destacado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nombre.setText("Nombre:");

        Combustible.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Combustible.setText("Combustible:");

        Potencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Potencia.setText("Potencia:");

        Categoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Categoria.setText("Categoria:");

        Consumo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Consumo.setText("Consumo:");

        Puertas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Puertas.setText("Numero de puertas:");

        Asientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Asientos.setText("Numero de asientos:");

        Precio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Precio.setText("Precio:");

        campoNombre.setEditable(false);
        campoNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoNombre.setBorder(null);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoCombustible.setEditable(false);
        campoCombustible.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoCombustible.setBorder(null);

        campoPotencia.setEditable(false);
        campoPotencia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPotencia.setBorder(null);

        campoCategoria.setEditable(false);
        campoCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoCategoria.setBorder(null);

        campoConsumo.setEditable(false);
        campoConsumo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoConsumo.setBorder(null);

        campoPuertas.setEditable(false);
        campoPuertas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPuertas.setBorder(null);

        campoAsientos.setEditable(false);
        campoAsientos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoAsientos.setBorder(null);

        campoPrecio.setEditable(false);
        campoPrecio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPrecio.setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Contacto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Contacto.setText("Contacto");

        cmpApellidosContacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cmpNombreContacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cmpNombreContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNombreContactoActionPerformed(evt);
            }
        });

        NombreContacto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NombreContacto.setText("Nombre");

        ApellidosContacto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ApellidosContacto.setText("Apellidos");

        MailContacto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MailContacto.setText("Correo Electrónico");

        cmpMailContacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        CiudadContacto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CiudadContacto.setText("Ciudad");

        cmpCiudadContacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Contacto)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CiudadContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnEnviar))
                    .addComponent(cmpNombreContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(cmpApellidosContacto)
                    .addComponent(cmpMailContacto)
                    .addComponent(cmpCiudadContacto)
                    .addComponent(ApellidosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Contacto)
                .addGap(4, 4, 4)
                .addComponent(NombreContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApellidosContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpApellidosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MailContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpMailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CiudadContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpCiudadContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        destacado.setText("Destacado");
        destacado.setToolTipText("");
        destacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destacadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Puertas)
                    .addComponent(Asientos)
                    .addComponent(Precio)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combustible)
                    .addComponent(Potencia)
                    .addComponent(Categoria)
                    .addComponent(Consumo)
                    .addComponent(destacado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCombustible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPotencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConsumo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPuertas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAsientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combustible)
                    .addComponent(campoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Potencia)
                    .addComponent(campoPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consumo)
                    .addComponent(campoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puertas)
                    .addComponent(campoPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asientos)
                    .addComponent(campoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destacado)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmpNombreContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNombreContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNombreContactoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String name = cmpNombreContacto.getText();
        String surname = cmpApellidosContacto.getText();
        String city = cmpCiudadContacto.getText();
        String mail = cmpMailContacto.getText();
        if (name.isEmpty() || surname.isEmpty() || city.isEmpty() || mail.isEmpty()) JOptionPane.showMessageDialog(null, "Por favor introduzca valores válidos");
        else {
            Form form = new Form();
            form.setParam("name", name);
            form.setParam("surname", surname);
            form.setParam("city", city);
            form.setParam("mail", mail);
            Controller.contactRequest(form, this.car.getName());
            JOptionPane.showMessageDialog(null, "¡Solicitud enviada con éxito!");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void destacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destacadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destacadoActionPerformed

    /**
     * Abre una nueva ventana
     * @param car Coche a mostrar en la nueva ventana
     */
    public static void openWindow(final CarModel car) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final CarWindow window = new CarWindow(car);
                //Cuando se cierre la ventana no se abandonará la aplicación entera
                window.addWindowListener(new WindowAdapter(){
                    @Override
                    public void windowClosing(WindowEvent e){
                        window.setVisible(false);
                        window.dispose();
                    }
                });
                window.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidosContacto;
    private javax.swing.JLabel Asientos;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel CiudadContacto;
    private javax.swing.JLabel Combustible;
    private javax.swing.JLabel Consumo;
    private javax.swing.JLabel Contacto;
    private javax.swing.JLabel MailContacto;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreContacto;
    private javax.swing.JLabel Potencia;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Puertas;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextField campoAsientos;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoCombustible;
    private javax.swing.JTextField campoConsumo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPotencia;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoPuertas;
    private javax.swing.JTextField cmpApellidosContacto;
    private javax.swing.JTextField cmpCiudadContacto;
    private javax.swing.JTextField cmpMailContacto;
    private javax.swing.JTextField cmpNombreContacto;
    private javax.swing.JCheckBox destacado;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
