package Admin;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Ventana de la ficha de un coche
 */
public class CarWindow extends javax.swing.JFrame {
    /*
     * Copyright (c) 1995, 2008, Oracle and/or its affiliates. All rights reserved.
     *
     * Redistribution and use in source and binary forms, with or without
     * modification, are permitted provided that the following conditions
     * are met:
     *
     *   - Redistributions of source code must retain the above copyright
     *     notice, this list of conditions and the following disclaimer.
     *
     *   - Redistributions in binary form must reproduce the above copyright
     *     notice, this list of conditions and the following disclaimer in the
     *     documentation and/or other materials provided with the distribution.
     *
     *   - Neither the name of Oracle or the names of its
     *     contributors may be used to endorse or promote products derived
     *     from this software without specific prior written permission.
     *
     * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
     * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
     * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
     * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     * 
     * Source code of imagenFileChooser based in FileChooser Swing tutorial: https://docs.oracle.com/javase/tutorial/uiswing/components/filechooser.html
     */
    
    /**
     * Coche del que tiene información esta ventana
     */
    private final CarModel car;

    /**
    * Flag para modificar o introducir
    */
    private final boolean accion;
    
    /**
     * Panel con la imagen del coche a subir al servidor
     */
    private final JFileChooser imageFileChooser;

    /**
     * Creates new form Descripcion
     *
     * @param car Coche a mostrar en el formulario
     * @param accion Si es true "modificar", si no "introducir"
     */
    public CarWindow(CarModel car, boolean accion) {
        this.accion=accion;
        initComponents();
        imageFileChooser = new JFileChooser();
        /*
         * Toolkit.createImage sólo soporta determinados formatos de imagen
         */
        imageFileChooser.setFileFilter(new FileNameExtensionFilter("GIF, JPG o PNG", "gif", "jpg", "jpeg", "png"));
        if (!accion) {
            btnModificar.setText("Introducir");
            campoNombre.setEditable(true);
        }
        this.car = car;
        campoNombre.setText(car.getName());
        campoAsientos.setText("" + car.getNumberSeats());
        campoCategoria.setText(car.getCategory());
        campoCombustible.setText(car.getFuelType());
        campoConsumo.setText("" + car.getConsumption());
        campoPotencia.setText("" + car.getPower());
        campoPrecio.setText("" + car.getCost());
        campoPuertas.setText("" + car.getNumberDoors());
        sobreescribirImagen.setSelected(false);
        destacado.setSelected(car.getFeatured());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Combustible = new javax.swing.JLabel();
        Potencia = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Consumo = new javax.swing.JLabel();
        Puertas = new javax.swing.JLabel();
        Asientos = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoCombustible = new javax.swing.JTextField();
        campoPotencia = new javax.swing.JTextField();
        campoCategoria = new javax.swing.JTextField();
        campoConsumo = new javax.swing.JTextField();
        campoPuertas = new javax.swing.JTextField();
        campoAsientos = new javax.swing.JTextField();
        campoPrecio = new javax.swing.JTextField();
        destacado = new javax.swing.JCheckBox();
        btnModificar = new javax.swing.JButton();
        campoImagen = new javax.swing.JTextField();
        Imagen = new javax.swing.JLabel();
        btnImagen = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        sobreescribirImagen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nombre.setText("Nombre:");

        Combustible.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Combustible.setText("Combustible:");

        Potencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Potencia.setText("Potencia(CV):");

        Categoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Categoria.setText("Categoria:");

        Consumo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Consumo.setText("Consumo(L/100km):");

        Puertas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Puertas.setText("Numero de puertas:");

        Asientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Asientos.setText("Numero de asientos:");

        Precio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Precio.setText("Precio(€):");

        campoNombre.setEditable(false);
        campoNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoNombre.setBorder(null);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoCombustible.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoCombustible.setBorder(null);

        campoPotencia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPotencia.setBorder(null);

        campoCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoCategoria.setBorder(null);

        campoConsumo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoConsumo.setBorder(null);

        campoPuertas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPuertas.setBorder(null);

        campoAsientos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoAsientos.setBorder(null);

        campoPrecio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPrecio.setBorder(null);

        destacado.setText("Destacado");
        destacado.setToolTipText("");
        destacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destacadoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        campoImagen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoImagen.setBorder(null);

        Imagen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Imagen.setText("Imagen:");

        btnImagen.setText("Buscar");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        sobreescribirImagen.setText("Sobrescribir imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sobreescribirImagen)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Puertas)
                            .addComponent(Asientos)
                            .addComponent(Precio)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combustible)
                            .addComponent(Potencia)
                            .addComponent(Categoria)
                            .addComponent(Consumo)
                            .addComponent(Imagen)
                            .addComponent(destacado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCombustible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPotencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoConsumo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPuertas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAsientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combustible)
                    .addComponent(campoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Potencia)
                    .addComponent(campoPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consumo)
                    .addComponent(campoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puertas)
                    .addComponent(campoPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asientos)
                    .addComponent(campoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imagen)
                    .addComponent(campoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagen)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobreescribirImagen)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destacado)
                    .addComponent(btnModificar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void destacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destacadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destacadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int seats, power, cost, doors;
        double consumption;
        try{
            seats = Integer.parseInt(campoAsientos.getText());
        } catch(Exception e){
            seats = 0;
        }
        try{
            consumption = Double.parseDouble(campoConsumo.getText());
        } catch(Exception e){
            consumption = 0.0;
        }try{
            power = Integer.parseInt(campoPotencia.getText());
        } catch(Exception e){
            power = 0;
        }
        try{
            cost = Integer.parseInt(campoPrecio.getText());
        } catch(Exception e){
            cost = 0;
        }
        try{
            doors = Integer.parseInt(campoPuertas.getText());
        } catch(Exception e){
            doors = 0;
        }
        
        car.setName(campoNombre.getText());
        car.setNumberSeats(seats);
        car.setCategory(campoCategoria.getText());
        car.setFuelType(campoCombustible.getText());
        car.setConsumption(consumption);
        car.setPower(power);
        car.setCost(cost);
        car.setNumberDoors(doors);
        car.setFeatured(destacado.isSelected());
        if (sobreescribirImagen.isSelected()){
            byte[] imgBytes = null;
            if (!campoImagen.getText().equals("")){
                try {
                    imgBytes = Files.readAllBytes((new File(campoImagen.getText())).toPath());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            car.setImg(imgBytes);
        }
        Controller.modify(car,accion);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        //Handle open button action.
        int returnVal = imageFileChooser.showOpenDialog(btnImagen);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = imageFileChooser.getSelectedFile();
            //This is where a real application would open the file.
            campoImagen.setText(file.getPath());
        } else {
            campoImagen.setText("");
        }
    }//GEN-LAST:event_btnImagenActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        campoImagen.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed


    /**
     * Abre una nueva ventana
     *
     * @param car Coche a mostrar en la nueva ventana
     * @param accion Si es true "modificar", si no "introducir"
     */
    public static void openWindow(final CarModel car, boolean accion) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final CarWindow window = new CarWindow(car, accion);
                //Cuando se cierre la ventana no se abandonará la aplicación entera
                window.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        window.setVisible(false);
                        window.dispose();
                    }
                });
                window.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asientos;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Combustible;
    private javax.swing.JLabel Consumo;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Potencia;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Puertas;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoAsientos;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoCombustible;
    private javax.swing.JTextField campoConsumo;
    private javax.swing.JTextField campoImagen;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPotencia;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoPuertas;
    private javax.swing.JCheckBox destacado;
    private javax.swing.JCheckBox sobreescribirImagen;
    // End of variables declaration//GEN-END:variables
}
