package Aplicacion;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana del buscador
 */
public class Buscador extends javax.swing.JFrame {
    
    private final HashMap<String,String> filtro = new HashMap<String, String>();
    private final DefaultTableModel tableModel = new DefaultTableModel(new Object[]{"Modelo", "Categoría", "Coste", "Potencia", "Combustible", "Consumo", ""}, 0);
    private final javax.swing.JTable modelsList = new javax.swing.JTable(tableModel);
    
    /**
     * Creates new form Buscador
     */
    public Buscador() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        modelo = new java.awt.Label();
        btn_buscar = new java.awt.Button();
        cb_modelo = new javax.swing.JComboBox();
        cb_combustible = new javax.swing.JComboBox();
        modelo1 = new java.awt.Label();
        modelo9 = new java.awt.Label();
        sld_potenciaMax = new javax.swing.JSlider();
        txt_potenciaMax = new javax.swing.JTextField();
        sld_potenciaMin = new javax.swing.JSlider();
        txt_potenciaMin = new javax.swing.JTextField();
        modelo10 = new java.awt.Label();
        cb_tipo = new javax.swing.JComboBox();
        modelo2 = new java.awt.Label();
        modelo3 = new java.awt.Label();
        sld_precioMin = new javax.swing.JSlider();
        txt_precioMin = new javax.swing.JTextField();
        sld_precioMax = new javax.swing.JSlider();
        txt_precioMax = new javax.swing.JTextField();
        modelo11 = new java.awt.Label();
        modelo12 = new java.awt.Label();
        sld_consumoMin = new javax.swing.JSlider();
        txt_consumoMax = new javax.swing.JTextField();
        sld_consumoMax = new javax.swing.JSlider();
        txt_consumoMin = new javax.swing.JTextField();
        modelo13 = new java.awt.Label();
        modelo14 = new java.awt.Label();
        modelo4 = new java.awt.Label();
        cb_puertas = new javax.swing.JComboBox();
        cb_asientos = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane(modelsList);

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(200);

        modelo.setName("Modelo"); // NOI18N
        modelo.setText("Modelo");

        btn_buscar.setLabel("Buscar");
        btn_buscar.setName("Buscar"); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cb_modelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "V5", "V4" }));
        cb_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_modeloActionPerformed(evt);
            }
        });

        cb_combustible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "Gasolina", "Gasoil" }));

        modelo1.setName("Modelo"); // NOI18N
        modelo1.setText("Tipo combustible");

        modelo9.setName("Potencia Max"); // NOI18N
        modelo9.setText("Potencia Max");

        sld_potenciaMax.setMaximum(200);
        sld_potenciaMax.setToolTipText("");
        sld_potenciaMax.setValue(100);
        sld_potenciaMax.setValueIsAdjusting(true);
        sld_potenciaMax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sld_potenciaMaxMouseDragged(evt);
            }
        });
        sld_potenciaMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sld_potenciaMaxMouseClicked(evt);
            }
        });
        sld_potenciaMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sld_potenciaMaxKeyPressed(evt);
            }
        });

        txt_potenciaMax.setEditable(false);
        txt_potenciaMax.setText("100");
        txt_potenciaMax.setToolTipText("Ej:  V20");
        txt_potenciaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_potenciaMaxActionPerformed(evt);
            }
        });

        sld_potenciaMin.setMaximum(200);
        sld_potenciaMin.setToolTipText("");
        sld_potenciaMin.setValue(100);
        sld_potenciaMin.setValueIsAdjusting(true);
        sld_potenciaMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sld_potenciaMinMouseDragged(evt);
            }
        });
        sld_potenciaMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sld_potenciaMinMouseClicked(evt);
            }
        });
        sld_potenciaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sld_potenciaMinKeyPressed(evt);
            }
        });

        txt_potenciaMin.setEditable(false);
        txt_potenciaMin.setText("100");
        txt_potenciaMin.setToolTipText("Ej:  V20");
        txt_potenciaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_potenciaMinActionPerformed(evt);
            }
        });

        modelo10.setName("Potencia Min"); // NOI18N
        modelo10.setText("Potencia Min");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "Familiar", "Deportivo", "Monovolumen", "Todo-terreno", "Mini" }));
        cb_tipo.setToolTipText("");
        cb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoActionPerformed(evt);
            }
        });

        modelo2.setName("Categoría"); // NOI18N
        modelo2.setText("Categoría");

        modelo3.setName("Numero puertas"); // NOI18N
        modelo3.setText("Numero puertas");

        sld_precioMin.setMaximum(100000);
        sld_precioMin.setToolTipText("");
        sld_precioMin.setValue(10000);
        sld_precioMin.setValueIsAdjusting(true);
        sld_precioMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sld_precioMinMouseDragged(evt);
            }
        });
        sld_precioMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sld_precioMinMouseClicked(evt);
            }
        });
        sld_precioMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sld_precioMinKeyPressed(evt);
            }
        });

        txt_precioMin.setEditable(false);
        txt_precioMin.setText("10000");
        txt_precioMin.setToolTipText("Ej:  V20");
        txt_precioMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioMinActionPerformed(evt);
            }
        });

        sld_precioMax.setMaximum(100000);
        sld_precioMax.setToolTipText("");
        sld_precioMax.setValue(10000);
        sld_precioMax.setValueIsAdjusting(true);
        sld_precioMax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sld_precioMaxMouseDragged(evt);
            }
        });
        sld_precioMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sld_precioMaxMouseClicked(evt);
            }
        });
        sld_precioMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sld_precioMaxKeyPressed(evt);
            }
        });

        txt_precioMax.setEditable(false);
        txt_precioMax.setText("10000");
        txt_precioMax.setToolTipText("Ej:  V20");
        txt_precioMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioMaxActionPerformed(evt);
            }
        });

        modelo11.setName("Precio Max"); // NOI18N
        modelo11.setText("Precio Max");

        modelo12.setName("Precio Min"); // NOI18N
        modelo12.setText("Precio Min");

        sld_consumoMin.setMaximum(20);
        sld_consumoMin.setToolTipText("");
        sld_consumoMin.setValue(5);
        sld_consumoMin.setValueIsAdjusting(true);
        sld_consumoMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sld_consumoMinMouseClicked(evt);
            }
        });
        sld_consumoMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sld_consumoMinMouseDragged(evt);
            }
        });
        sld_consumoMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sld_consumoMinKeyPressed(evt);
            }
        });

        txt_consumoMax.setEditable(false);
        txt_consumoMax.setText("5");
        txt_consumoMax.setToolTipText("Ej:  V20");
        txt_consumoMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_consumoMaxActionPerformed(evt);
            }
        });

        sld_consumoMax.setMaximum(20);
        sld_consumoMax.setToolTipText("");
        sld_consumoMax.setValue(5);
        sld_consumoMax.setValueIsAdjusting(true);
        sld_consumoMax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sld_consumoMaxMouseDragged(evt);
            }
        });
        sld_consumoMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sld_consumoMaxMouseClicked(evt);
            }
        });
        sld_consumoMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sld_consumoMaxKeyPressed(evt);
            }
        });

        txt_consumoMin.setEditable(false);
        txt_consumoMin.setText("5");
        txt_consumoMin.setToolTipText("Ej:  V20");
        txt_consumoMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_consumoMinActionPerformed(evt);
            }
        });

        modelo13.setName("Consumo Max"); // NOI18N
        modelo13.setText("Consumo Max (l/100km)");

        modelo14.setName("Consumo Min"); // NOI18N
        modelo14.setText("Consumo Min (l/100km)");

        modelo4.setName("Numero asientos"); // NOI18N
        modelo4.setText("Numero asientos");

        cb_puertas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "1", "2", "3", "4", "5", "6" }));
        cb_puertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_puertasActionPerformed(evt);
            }
        });

        cb_asientos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_asientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_asientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(modelo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sld_potenciaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_potenciaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modelo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(modelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sld_potenciaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_potenciaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modelo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(modelo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modelo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(modelo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sld_precioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sld_precioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_precioMax, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txt_precioMin))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modelo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sld_consumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_consumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sld_consumoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_consumoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(215, 215, 215))))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sld_precioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_precioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sld_precioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_precioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_combustible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_potenciaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sld_potenciaMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_potenciaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sld_potenciaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelo9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sld_consumoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_consumoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sld_consumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_consumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(modelo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modelo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modelo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_asientos)
                            .addComponent(modelo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modelo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(modelo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        modelo.getAccessibleContext().setAccessibleName("txt_modelo");
        modelo10.getAccessibleContext().setAccessibleName("Potencia Min");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_potenciaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_potenciaMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_potenciaMaxActionPerformed

    private void sld_potenciaMaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_potenciaMaxMouseDragged
        // TODO add your handling code here:
         txt_potenciaMax.setText(String.valueOf(sld_potenciaMax.getValue()));
    }//GEN-LAST:event_sld_potenciaMaxMouseDragged

    private void sld_potenciaMinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_potenciaMinMouseDragged
        // TODO add your handling code here:
        txt_potenciaMin.setText(String.valueOf(sld_potenciaMin.getValue()));
    }//GEN-LAST:event_sld_potenciaMinMouseDragged

    private void txt_potenciaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_potenciaMinActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_potenciaMinActionPerformed

    private void sld_potenciaMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sld_potenciaMinKeyPressed
        // TODO add your handling code here:
                txt_potenciaMin.setText(String.valueOf(sld_potenciaMin.getValue()));

    }//GEN-LAST:event_sld_potenciaMinKeyPressed

    private void sld_potenciaMaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sld_potenciaMaxKeyPressed
        // TODO add your handling code here:
        txt_potenciaMax.setText(String.valueOf(sld_potenciaMax.getValue()));
    }//GEN-LAST:event_sld_potenciaMaxKeyPressed

    private void cb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipoActionPerformed

    private void sld_precioMinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_precioMinMouseDragged
        // TODO add your handling code here:
     txt_precioMin.setText(String.valueOf(sld_precioMin.getValue()));

    }//GEN-LAST:event_sld_precioMinMouseDragged

    private void sld_precioMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sld_precioMinKeyPressed
        // TODO add your handling code here:
             txt_precioMin.setText(String.valueOf(sld_precioMin.getValue()));

    }//GEN-LAST:event_sld_precioMinKeyPressed

    private void txt_precioMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioMinActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_precioMinActionPerformed

    private void sld_precioMaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_precioMaxMouseDragged
        // TODO add your handling code here:
             txt_precioMax.setText(String.valueOf(sld_precioMax.getValue()));

    }//GEN-LAST:event_sld_precioMaxMouseDragged

    private void sld_precioMaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sld_precioMaxKeyPressed
        // TODO add your handling code here:
             txt_precioMax.setText(String.valueOf(sld_precioMax.getValue()));

    }//GEN-LAST:event_sld_precioMaxKeyPressed

    private void txt_precioMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioMaxActionPerformed

    private void sld_consumoMinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_consumoMinMouseDragged
        // TODO add your handling code here:
             txt_consumoMin.setText(String.valueOf(sld_consumoMin.getValue()));

    }//GEN-LAST:event_sld_consumoMinMouseDragged

    private void sld_consumoMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sld_consumoMinKeyPressed
        // TODO add your handling code here:
             txt_consumoMin.setText(String.valueOf(sld_consumoMin.getValue()));

    }//GEN-LAST:event_sld_consumoMinKeyPressed

    private void txt_consumoMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_consumoMaxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_consumoMaxActionPerformed

    private void sld_consumoMaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_consumoMaxMouseDragged
        // TODO add your handling code here:
             txt_consumoMax.setText(String.valueOf(sld_consumoMax.getValue()));

    }//GEN-LAST:event_sld_consumoMaxMouseDragged

    private void sld_consumoMaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sld_consumoMaxKeyPressed
        // TODO add your handling code here:
             txt_consumoMax.setText(String.valueOf(sld_consumoMax.getValue()));

    }//GEN-LAST:event_sld_consumoMaxKeyPressed

    private void txt_consumoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_consumoMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_consumoMinActionPerformed

    private void cb_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_modeloActionPerformed

    private void cb_puertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_puertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_puertasActionPerformed

    private void cb_asientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_asientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_asientosActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        //IAR- Van a tener valores y ser enteros si o si
	     filtro.put("consumptionMax", this.txt_consumoMax.getText());
             filtro.put("consumptionMin", this.txt_consumoMin.getText());
             filtro.put("powerMax", this.txt_potenciaMax.getText());
             filtro.put("powerMin", this.txt_potenciaMin.getText());
             filtro.put("costMax", this.txt_precioMax.getText());
             filtro.put("costMin", this.txt_precioMin.getText());
   

            boolean tieneValor=!(this.cb_asientos.getSelectedItem().toString().equals("Todos") || 
                    this.cb_asientos.getSelectedItem().toString().equals("Cualquiera"));
            if(tieneValor) filtro.put("numberSeats", this.cb_asientos.getSelectedItem().toString());
       
            tieneValor=!(this.cb_combustible.getSelectedItem().toString().equals("Todos") || 
                    this.cb_combustible.getSelectedItem().toString().equals("Cualquiera"));
            if(tieneValor) filtro.put("fuelType", this.cb_combustible.getSelectedItem().toString());
        
            tieneValor=!(this.cb_modelo.getSelectedItem().toString().equals("Todos") || 
                    this.cb_modelo.getSelectedItem().toString().equals("Cualquiera"));
            if(tieneValor) filtro.put("name", this.cb_modelo.getSelectedItem().toString());
         
            
            tieneValor=!(this.cb_puertas.getSelectedItem().toString().equals("Todos") || 
                    this.cb_puertas.getSelectedItem().toString().equals("Cualquiera"));
            if(tieneValor) filtro.put("numberDoors", this.cb_puertas.getSelectedItem().toString());
            
            tieneValor=!(this.cb_tipo.getSelectedItem().toString().equals("Todos") || 
                    this.cb_tipo.getSelectedItem().toString().equals("Cualquiera"));
            if(tieneValor) filtro.put("category", this.cb_tipo.getSelectedItem().toString());

        String texto = "";
        Iterator iter = (Iterator) filtro.keySet().iterator();
        Set<String> keySet = filtro.keySet();
        Iterator<String> keySetIterator = keySet.iterator();

        while(keySetIterator.hasNext()) {
            String key = keySetIterator.next();
            texto += key + " - " + filtro.get(key) + " \n";
        }
        
        Form formulario_filtro = new Form(filtro);
        Controller.list(formulario_filtro, modelsList);
        filtro.clear();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void sld_potenciaMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_potenciaMinMouseClicked
        // TODO add your handling code here:
                     txt_potenciaMin.setText(String.valueOf(sld_potenciaMin.getValue()));

    }//GEN-LAST:event_sld_potenciaMinMouseClicked

    private void sld_potenciaMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_potenciaMaxMouseClicked
        // TODO add your handling code here:
                     txt_potenciaMax.setText(String.valueOf(sld_potenciaMax.getValue()));

    }//GEN-LAST:event_sld_potenciaMaxMouseClicked

    private void sld_consumoMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_consumoMinMouseClicked
        // TODO add your handling code here:
                     txt_consumoMin.setText(String.valueOf(sld_consumoMin.getValue()));

    }//GEN-LAST:event_sld_consumoMinMouseClicked

    private void sld_consumoMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_consumoMaxMouseClicked
        // TODO add your handling code here:
                     txt_consumoMax.setText(String.valueOf(sld_consumoMax.getValue()));

    }//GEN-LAST:event_sld_consumoMaxMouseClicked

    private void sld_precioMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_precioMaxMouseClicked
        // TODO add your handling code here:
                     txt_precioMax.setText(String.valueOf(sld_precioMax.getValue()));

    }//GEN-LAST:event_sld_precioMaxMouseClicked

    private void sld_precioMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sld_precioMinMouseClicked
        // TODO add your handling code here:
                     txt_precioMin.setText(String.valueOf(sld_precioMin.getValue()));

    }//GEN-LAST:event_sld_precioMinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Buscador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_buscar;
    private javax.swing.JComboBox cb_asientos;
    private javax.swing.JComboBox cb_combustible;
    private javax.swing.JComboBox cb_modelo;
    private javax.swing.JComboBox cb_puertas;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label modelo;
    private java.awt.Label modelo1;
    private java.awt.Label modelo10;
    private java.awt.Label modelo11;
    private java.awt.Label modelo12;
    private java.awt.Label modelo13;
    private java.awt.Label modelo14;
    private java.awt.Label modelo2;
    private java.awt.Label modelo3;
    private java.awt.Label modelo4;
    private java.awt.Label modelo9;
    private javax.swing.JSlider sld_consumoMax;
    private javax.swing.JSlider sld_consumoMin;
    private javax.swing.JSlider sld_potenciaMax;
    private javax.swing.JSlider sld_potenciaMin;
    private javax.swing.JSlider sld_precioMax;
    private javax.swing.JSlider sld_precioMin;
    private javax.swing.JTextField txt_consumoMax;
    private javax.swing.JTextField txt_consumoMin;
    private javax.swing.JTextField txt_potenciaMax;
    private javax.swing.JTextField txt_potenciaMin;
    private javax.swing.JTextField txt_precioMax;
    private javax.swing.JTextField txt_precioMin;
    // End of variables declaration//GEN-END:variables
}
